#!/bin/bash

set -e

if [ -z $STACK_PREFIX ]; then
    STACK_PREFIX="csa-v1"
fi

STACK_CORE_FUNCTIONS="${STACK_PREFIX}-core-functions"
STACK_CORE_BUCKETS="${STACK_PREFIX}-core-buckets"
STACK_CORE_VPC="${STACK_PREFIX}-core-vpc"
STACK_CORE_SGS="${STACK_PREFIX}-core-security-groups"
STACK_APP_INFRA="${STACK_PREFIX}-app-infra"
STACK_DEV_INSTANCE="${STACK_PREFIX}-dev-instance"

DEV_INSTANCE=$(aws cloudformation describe-stacks --stack-name $STACK_DEV_INSTANCE | jq -r -c '.Stacks[0].Outputs[] | select(.OutputKey == "PublicDnsName") | .OutputValue')
echo "DEV_INSTANCE_SSH_ENDPOINT: ssh ec2-user@$DEV_INSTANCE"

OPEN_SEARCH_ENDPOINT=$(aws ssm get-parameter --name "${STACK_PREFIX}-app-infra-open-search-endpoint" --query "Parameter.Value")
echo "OPEN_SEARCH_ENDPOINT: ${OPEN_SEARCH_ENDPOINT}"

OPEN_SEARCH_DASHBOARD_URL=$(aws cloudformation describe-stacks --stack-name $STACK_APP_INFRA | jq -r -c '.Stacks[0].Outputs[] | select(.OutputKey == "NginxInstanceDNS") | .OutputValue')
echo "OPEN_SEARCH_DASHBOARD_URL: https://$OPEN_SEARCH_DASHBOARD_URL/_dashboards"

